import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User.js';
import Book from './models/Book.js';

dotenv.config();

const seedDatabase = async() => {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/kithab');
        console.log('MongoDB connected for seeding...');

        // Clear existing data
        await User.deleteMany({});
        await Book.deleteMany({});
        console.log('Cleared existing data');

        // Create sample users
        const users = await User.create([{
                name: 'John Smith',
                email: 'john@example.com',
                password: 'password123',
                phone: '+1-555-0101',
                address: { city: 'New York', state: 'NY', zipCode: '10001' },
                profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
                bio: 'Book lover and avid reader',
            },
            {
                name: 'Sarah Johnson',
                email: 'sarah@example.com',
                password: 'password123',
                phone: '+1-555-0102',
                address: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
                bio: 'Fiction enthusiast',
            },
            {
                name: 'Michael Chen',
                email: 'michael@example.com',
                password: 'password123',
                phone: '+1-555-0103',
                address: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
                bio: 'Tech books and self-improvement fan',
            },
            {
                name: 'Emma Wilson',
                email: 'emma@example.com',
                password: 'password123',
                phone: '+1-555-0104',
                address: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
                bio: 'History and biography lover',
            },
            {
                name: 'David Brown',
                email: 'david@example.com',
                password: 'password123',
                phone: '+1-555-0105',
                address: { city: 'Boston', state: 'MA', zipCode: '02101' },
                profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
                bio: 'Science and philosophy books',
            },
        ]);

        console.log(`Created ${users.length} users`);

        // Helper function to generate book cover image URL using Open Library API
        // with multiple quality options and fallbacks for better resolution
        const getBookCoverUrl = (title, author) => {
            // Using Open Library Covers API with title and author query
            // Format: https://covers.openlibrary.org/b/{cover_type}/{identifier}-{size}.jpg
            // Using size L (Large) for high-resolution, clear images (600x900px typical)
            const encodedTitle = encodeURIComponent(title);
            const encodedAuthor = encodeURIComponent(author);

            // Primary: Open Library with Large resolution (-L)
            const openLibraryUrl = `https://covers.openlibrary.org/b/title/${encodedTitle}-L.jpg`;

            // Size L provides best clarity (typical 600x900 pixels)
            // This gives professional book cover quality images
            return openLibraryUrl;
        };

        // Create sample books
        const booksData = [
            // Fiction
            {
                title: 'The Great Gatsby',
                author: 'F. Scott Fitzgerald',
                description: 'A classic American novel set in the Jazz Age.',
                category: 'Fiction',
                price: 250,
                condition: 'Good',
                yearPublished: 1925,
                yearPurchased: 2020,
                images: [getBookCoverUrl('The Great Gatsby', 'F. Scott Fitzgerald')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'To Kill a Mockingbird',
                author: 'Harper Lee',
                description: 'A gripping tale of racial injustice and childhood innocence.',
                category: 'Fiction',
                price: 280,
                condition: 'Like New',
                yearPublished: 1960,
                yearPurchased: 2021,
                images: [getBookCoverUrl('To Kill a Mockingbird', 'Harper Lee')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: '1984',
                author: 'George Orwell',
                description: 'A dystopian social science fiction novel.',
                category: 'Fiction',
                price: 300,
                condition: 'Good',
                yearPublished: 1949,
                yearPurchased: 2019,
                images: [getBookCoverUrl('1984', 'George Orwell')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'Pride and Prejudice',
                author: 'Jane Austen',
                description: 'A romantic novel of manners and marriage.',
                category: 'Fiction',
                price: 220,
                condition: 'Fair',
                yearPublished: 1813,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Pride and Prejudice', 'Jane Austen')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: false },
            },

            // Non-Fiction
            {
                title: 'Sapiens',
                author: 'Yuval Noah Harari',
                description: 'A brief history of humankind from the Stone Age to modern times.',
                category: 'Non-Fiction',
                price: 450,
                condition: 'Like New',
                yearPublished: 2011,
                yearPurchased: 2023,
                images: [getBookCoverUrl('Sapiens', 'Yuval Noah Harari')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Thinking, Fast and Slow',
                author: 'Daniel Kahneman',
                description: 'Insights into the two systems of thought that drive our behavior.',
                category: 'Non-Fiction',
                price: 380,
                condition: 'Good',
                yearPublished: 2011,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Thinking, Fast and Slow', 'Daniel Kahneman')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Science
            {
                title: 'A Brief History of Time',
                author: 'Stephen Hawking',
                description: 'From the Big Bang to Black Holes - an exploration of space and time.',
                category: 'Science',
                price: 350,
                condition: 'Good',
                yearPublished: 1988,
                yearPurchased: 2020,
                images: [getBookCoverUrl('A Brief History of Time', 'Stephen Hawking')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Selfish Gene',
                author: 'Richard Dawkins',
                description: 'A revolutionary look at evolution and natural selection.',
                category: 'Science',
                price: 320,
                condition: 'Fair',
                yearPublished: 1976,
                yearPurchased: 2019,
                images: [getBookCoverUrl('The Selfish Gene', 'Richard Dawkins')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'Cosmos',
                author: 'Carl Sagan',
                description: 'A journey through space and time exploring the universe.',
                category: 'Science',
                price: 420,
                condition: 'Like New',
                yearPublished: 1980,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Cosmos', 'Carl Sagan')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // History
            {
                title: 'The Art of War',
                author: 'Sun Tzu',
                description: 'Ancient Chinese military treatise on strategy and warfare.',
                category: 'History',
                price: 180,
                condition: 'Good',
                yearPublished: 2012,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Art of War', 'Sun Tzu')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Rise and Fall of the Third Reich',
                author: 'William L. Shirer',
                description: 'A comprehensive history of Nazi Germany and World War II.',
                category: 'History',
                price: 550,
                condition: 'Good',
                yearPublished: 1960,
                yearPurchased: 2020,
                images: [getBookCoverUrl('The Rise and Fall of the Third Reich', 'William L. Shirer')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'A History of Ancient Rome',
                author: 'Michael Grant',
                description: 'The definitive account of Rome from its origins to the end of the empire.',
                category: 'History',
                price: 480,
                condition: 'Fair',
                yearPublished: 2005,
                yearPurchased: 2021,
                images: [getBookCoverUrl('A History of Ancient Rome', 'Michael Grant')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: false, shipping: true },
            },

            // Biography
            {
                title: 'Steve Jobs',
                author: 'Walter Isaacson',
                description: 'The exclusive biography of the Apple founder.',
                category: 'Biography',
                price: 400,
                condition: 'Like New',
                yearPublished: 2011,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Steve Jobs', 'Walter Isaacson')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Churchill: A Life',
                author: 'Martin Gilbert',
                description: 'The definitive biography of Winston Churchill.',
                category: 'Biography',
                price: 520,
                condition: 'Good',
                yearPublished: 1991,
                yearPurchased: 2020,
                images: [getBookCoverUrl('Churchill: A Life', 'Martin Gilbert')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Einstein: A Life',
                author: 'Michael White',
                description: 'A fascinating biography of the genius physicist.',
                category: 'Biography',
                price: 380,
                condition: 'Good',
                yearPublished: 2005,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Einstein: A Life', 'Michael White')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Self-Help
            {
                title: 'Atomic Habits',
                author: 'James Clear',
                description: 'Transform your life by building small, powerful habits.',
                category: 'Self-Help',
                price: 320,
                condition: 'Like New',
                yearPublished: 2018,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Atomic Habits', 'James Clear')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The 7 Habits of Highly Effective People',
                author: 'Stephen R. Covey',
                description: 'Powerful lessons in personal change and effectiveness.',
                category: 'Self-Help',
                price: 280,
                condition: 'Fair',
                yearPublished: 1989,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The 7 Habits of Highly Effective People', 'Stephen R. Covey')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: false },
            },

            // Technology
            {
                title: 'Clean Code',
                author: 'Robert C. Martin',
                description: 'A handbook of agile software craftsmanship.',
                category: 'Technology',
                price: 450,
                condition: 'Good',
                yearPublished: 2008,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Clean Code', 'Robert C. Martin')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Pragmatic Programmer',
                author: 'David Thomas, Andrew Hunt',
                description: 'Your journey to mastery in programming.',
                category: 'Technology',
                price: 380,
                condition: 'Like New',
                yearPublished: 2019,
                yearPurchased: 2022,
                images: [getBookCoverUrl('The Pragmatic Programmer', 'David Thomas')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Introduction to Algorithms',
                author: 'Thomas H. Cormen',
                description: 'Comprehensive introduction to modern algorithms.',
                category: 'Technology',
                price: 650,
                condition: 'Good',
                yearPublished: 2009,
                yearPurchased: 2020,
                images: [getBookCoverUrl('Introduction to Algorithms', 'Thomas H. Cormen')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: false, shipping: true },
            },

            // Education
            {
                title: 'The Learning Brain',
                author: 'Uta Frith',
                description: 'Understanding how people learn and develop cognitive skills.',
                category: 'Education',
                price: 320,
                condition: 'Fair',
                yearPublished: 2018,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Learning Brain', 'Uta Frith')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Make It Stick',
                author: 'Peter C. Brown',
                description: 'The science of successful learning.',
                category: 'Education',
                price: 350,
                condition: 'Good',
                yearPublished: 2014,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Make It Stick', 'Peter C. Brown')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Fiction Books
            {
                title: 'The Catcher in the Rye',
                author: 'J.D. Salinger',
                description: 'A novel about teenage rebellion and alienation.',
                category: 'Fiction',
                price: 220,
                condition: 'Good',
                yearPublished: 1951,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Catcher in the Rye', 'J.D. Salinger')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Wuthering Heights',
                author: 'Emily Brontë',
                description: 'A dark gothic romance set on the Yorkshire moors.',
                category: 'Fiction',
                price: 240,
                condition: 'Like New',
                yearPublished: 1847,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Wuthering Heights', 'Emily Brontë')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Jane Eyre',
                author: 'Charlotte Brontë',
                description: 'A story of love, independence, and self-discovery.',
                category: 'Fiction',
                price: 280,
                condition: 'Good',
                yearPublished: 1847,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Jane Eyre', 'Charlotte Brontë')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'The Hobbit',
                author: 'J.R.R. Tolkien',
                description: 'An epic fantasy adventure of a reluctant hero.',
                category: 'Fiction',
                price: 320,
                condition: 'Good',
                yearPublished: 1937,
                yearPurchased: 2020,
                images: [getBookCoverUrl('The Hobbit', 'J.R.R. Tolkien')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Lord of the Rings',
                author: 'J.R.R. Tolkien',
                description: 'The epic conclusion to the fantasy trilogy.',
                category: 'Fiction',
                price: 450,
                condition: 'Like New',
                yearPublished: 1954,
                yearPurchased: 2022,
                images: [getBookCoverUrl('The Lord of the Rings', 'J.R.R. Tolkien')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Harry Potter and the Philosopher\'s Stone',
                author: 'J.K. Rowling',
                description: 'The beginning of a magical journey at Hogwarts.',
                category: 'Fiction',
                price: 300,
                condition: 'Good',
                yearPublished: 1997,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Harry Potter', 'J.K. Rowling')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Moby Dick',
                author: 'Herman Melville',
                description: 'A tale of obsession and the pursuit of a white whale.',
                category: 'Fiction',
                price: 260,
                condition: 'Fair',
                yearPublished: 1851,
                yearPurchased: 2020,
                images: [getBookCoverUrl('Moby Dick', 'Herman Melville')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'The Count of Monte Cristo',
                author: 'Alexandre Dumas',
                description: 'An epic story of revenge and redemption.',
                category: 'Fiction',
                price: 380,
                condition: 'Good',
                yearPublished: 1844,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Count of Monte Cristo', 'Alexandre Dumas')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Non-Fiction Books
            {
                title: 'Educated',
                author: 'Tara Westover',
                description: 'A memoir of a woman raised by survivalists who pursues education.',
                category: 'Non-Fiction',
                price: 420,
                condition: 'Like New',
                yearPublished: 2018,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Educated', 'Tara Westover')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Guns, Germs, and Steel',
                author: 'Jared Diamond',
                description: 'Why some civilizations conquered others.',
                category: 'Non-Fiction',
                price: 480,
                condition: 'Good',
                yearPublished: 1997,
                yearPurchased: 2020,
                images: [getBookCoverUrl('Guns, Germs, and Steel', 'Jared Diamond')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Mindset',
                author: 'Carol S. Dweck',
                description: 'How our beliefs shape who we become.',
                category: 'Non-Fiction',
                price: 350,
                condition: 'Good',
                yearPublished: 2006,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Mindset', 'Carol S. Dweck')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Immortal Life of Henrietta Lacks',
                author: 'Rebecca Skloot',
                description: 'The story of the woman behind medical breakthroughs.',
                category: 'Non-Fiction',
                price: 380,
                condition: 'Like New',
                yearPublished: 2010,
                yearPurchased: 2022,
                images: [getBookCoverUrl('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Checklist Manifesto',
                author: 'Atul Gawande',
                description: 'How simple checklists improve complex systems.',
                category: 'Non-Fiction',
                price: 300,
                condition: 'Good',
                yearPublished: 2009,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Checklist Manifesto', 'Atul Gawande')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Science Books
            {
                title: 'The Gene',
                author: 'Siddhartha Mukherjee',
                description: 'A comprehensive history of genetics and molecular biology.',
                category: 'Science',
                price: 520,
                condition: 'Good',
                yearPublished: 2016,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Gene', 'Siddhartha Mukherjee')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Structure of Scientific Revolutions',
                author: 'Thomas S. Kuhn',
                description: 'How science changes through paradigm shifts.',
                category: 'Science',
                price: 340,
                condition: 'Fair',
                yearPublished: 1962,
                yearPurchased: 2020,
                images: [getBookCoverUrl('The Structure of Scientific Revolutions', 'Thomas S. Kuhn')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'The Elegant Universe',
                author: 'Brian Greene',
                description: 'String theory and the nature of reality.',
                category: 'Science',
                price: 420,
                condition: 'Good',
                yearPublished: 1999,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Elegant Universe', 'Brian Greene')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional History Books
            {
                title: 'The Decline and Fall of the Roman Empire',
                author: 'Edward Gibbon',
                description: 'A monumental work on the fall of Rome.',
                category: 'History',
                price: 620,
                condition: 'Good',
                yearPublished: 1776,
                yearPurchased: 2019,
                images: [getBookCoverUrl('The Decline and Fall of the Roman Empire', 'Edward Gibbon')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: '1491: New Revelations of the Americas Before Columbus',
                author: 'Charles C. Mann',
                description: 'Rethinking pre-Columbian history.',
                category: 'History',
                price: 420,
                condition: 'Like New',
                yearPublished: 2005,
                yearPurchased: 2022,
                images: [getBookCoverUrl('1491', 'Charles C. Mann')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Cold War',
                author: 'John Lewis Gaddis',
                description: 'A comprehensive history of the Cold War era.',
                category: 'History',
                price: 480,
                condition: 'Good',
                yearPublished: 2005,
                yearPurchased: 2020,
                images: [getBookCoverUrl('The Cold War', 'John Lewis Gaddis')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: false, shipping: true },
            },

            // Additional Biography Books
            {
                title: 'Leonardo da Vinci',
                author: 'Walter Isaacson',
                description: 'A biography of the Renaissance genius.',
                category: 'Biography',
                price: 480,
                condition: 'Good',
                yearPublished: 2017,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Leonardo da Vinci', 'Walter Isaacson')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Benjamin Franklin',
                author: 'Walter Isaacson',
                description: 'The life of America\'s Founding Father.',
                category: 'Biography',
                price: 450,
                condition: 'Like New',
                yearPublished: 2003,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Benjamin Franklin', 'Walter Isaacson')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Oppenheimer',
                author: 'Martin J. Sherwin',
                description: 'The story of the father of the atomic bomb.',
                category: 'Biography',
                price: 520,
                condition: 'Good',
                yearPublished: 2020,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Oppenheimer', 'Martin J. Sherwin')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Self-Help Books
            {
                title: 'The Power of Habit',
                author: 'Charles Duhigg',
                description: 'Why we do what we do and how to change.',
                category: 'Self-Help',
                price: 340,
                condition: 'Good',
                yearPublished: 2012,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Power of Habit', 'Charles Duhigg')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Deep Work',
                author: 'Cal Newport',
                description: 'Rules for focused success in a distracted world.',
                category: 'Self-Help',
                price: 360,
                condition: 'Like New',
                yearPublished: 2016,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Deep Work', 'Cal Newport')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The 4-Hour Body',
                author: 'Tim Ferriss',
                description: 'An uncommon guide to rapid fat loss.',
                category: 'Self-Help',
                price: 420,
                condition: 'Good',
                yearPublished: 2010,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The 4-Hour Body', 'Tim Ferriss')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Technology Books
            {
                title: 'Code Complete',
                author: 'Steve McConnell',
                description: 'A practical handbook for software construction.',
                category: 'Technology',
                price: 520,
                condition: 'Good',
                yearPublished: 2004,
                yearPurchased: 2020,
                images: [getBookCoverUrl('Code Complete', 'Steve McConnell')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Design Patterns',
                author: 'Gang of Four',
                description: 'Elements of reusable object-oriented software.',
                category: 'Technology',
                price: 680,
                condition: 'Fair',
                yearPublished: 1994,
                yearPurchased: 2019,
                images: [getBookCoverUrl('Design Patterns', 'Gang of Four')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'The Mythical Man-Month',
                author: 'Frederick P. Brooks Jr.',
                description: 'Essays on software project management.',
                category: 'Technology',
                price: 380,
                condition: 'Good',
                yearPublished: 1975,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Mythical Man-Month', 'Frederick P. Brooks Jr.')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Education Books
            {
                title: 'Why Don\'t Students Like School?',
                author: 'Daniel T. Willingham',
                description: 'A cognitive scientist on understanding how we learn.',
                category: 'Education',
                price: 340,
                condition: 'Good',
                yearPublished: 2009,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Why Don\'t Students Like School', 'Daniel T. Willingham')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Mindsets and Grit',
                author: 'Angela Duckworth',
                description: 'The power of passion and perseverance.',
                category: 'Education',
                price: 360,
                condition: 'Like New',
                yearPublished: 2016,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Grit', 'Angela Duckworth')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },

            // Additional Mixed Genres
            {
                title: 'The Alchemist',
                author: 'Paulo Coelho',
                description: 'A philosophical fable about following your dreams.',
                category: 'Fiction',
                price: 280,
                condition: 'Good',
                yearPublished: 1988,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Alchemist', 'Paulo Coelho')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Slaughterhouse-Five',
                author: 'Kurt Vonnegut',
                description: 'An anti-war science fiction classic.',
                category: 'Fiction',
                price: 300,
                condition: 'Fair',
                yearPublished: 1969,
                yearPurchased: 2020,
                images: [getBookCoverUrl('Slaughterhouse-Five', 'Kurt Vonnegut')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: false, shipping: true },
            },
            {
                title: 'The Book Thief',
                author: 'Markus Zusak',
                description: 'A story told by Death during Nazi Germany.',
                category: 'Fiction',
                price: 340,
                condition: 'Good',
                yearPublished: 2005,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Book Thief', 'Markus Zusak')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Hunger Games',
                author: 'Suzanne Collins',
                description: 'A dystopian novel about survival and rebellion.',
                category: 'Fiction',
                price: 320,
                condition: 'Good',
                yearPublished: 2008,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Hunger Games', 'Suzanne Collins')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Becoming',
                author: 'Michelle Obama',
                description: 'The memoir of the former First Lady.',
                category: 'Biography',
                price: 420,
                condition: 'Like New',
                yearPublished: 2018,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Becoming', 'Michelle Obama')],
                seller: users[4]._id,
                location: { city: 'Boston', state: 'MA', zipCode: '02101' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'A Brief History of Nearly Everything',
                author: 'Bill Bryson',
                description: 'A fascinating exploration of science and nature.',
                category: 'Non-Fiction',
                price: 450,
                condition: 'Good',
                yearPublished: 2003,
                yearPurchased: 2020,
                images: [getBookCoverUrl('A Brief History of Nearly Everything', 'Bill Bryson')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Tipping Point',
                author: 'Malcolm Gladwell',
                description: 'How little things can make a big difference.',
                category: 'Non-Fiction',
                price: 360,
                condition: 'Good',
                yearPublished: 2000,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Tipping Point', 'Malcolm Gladwell')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Outliers',
                author: 'Malcolm Gladwell',
                description: 'The story of success.',
                category: 'Non-Fiction',
                price: 380,
                condition: 'Good',
                yearPublished: 2008,
                yearPurchased: 2021,
                images: [getBookCoverUrl('Outliers', 'Malcolm Gladwell')],
                seller: users[1]._id,
                location: { city: 'Los Angeles', state: 'CA', zipCode: '90001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'A Man\'s Search for Meaning',
                author: 'Viktor Frankl',
                description: 'Finding purpose in the midst of suffering.',
                category: 'Self-Help',
                price: 300,
                condition: 'Good',
                yearPublished: 1946,
                yearPurchased: 2021,
                images: [getBookCoverUrl('A Man\'s Search for Meaning', 'Viktor Frankl')],
                seller: users[2]._id,
                location: { city: 'San Francisco', state: 'CA', zipCode: '94102' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'Quiet',
                author: 'Susan Cain',
                description: 'The power of introverts in a world that can\'t stop talking.',
                category: 'Self-Help',
                price: 340,
                condition: 'Like New',
                yearPublished: 2012,
                yearPurchased: 2022,
                images: [getBookCoverUrl('Quiet', 'Susan Cain')],
                seller: users[3]._id,
                location: { city: 'Chicago', state: 'IL', zipCode: '60601' },
                deliveryOptions: { pickup: true, shipping: true },
            },
            {
                title: 'The Subtle Art of Not Giving a Fuck',
                author: 'Mark Manson',
                description: 'A counterintuitive approach to living a good life.',
                category: 'Self-Help',
                price: 320,
                condition: 'Good',
                yearPublished: 2016,
                yearPurchased: 2021,
                images: [getBookCoverUrl('The Subtle Art of Not Giving a Fuck', 'Mark Manson')],
                seller: users[0]._id,
                location: { city: 'New York', state: 'NY', zipCode: '10001' },
                deliveryOptions: { pickup: true, shipping: true },
            },
        ];

        // Create books and update user's booksListed
        for (const bookData of booksData) {
            const book = await Book.create(bookData);

            // Add book to seller's booksListed
            await User.findByIdAndUpdate(bookData.seller, {
                $push: { booksListed: book._id },
            });
        }

        console.log(`Created ${booksData.length} books`);

        // Add some reviews to books
        const books = await Book.find();
        if (books.length > 0) {
            // Add reviews to first few books
            for (let i = 0; i < Math.min(5, books.length); i++) {
                books[i].reviews.push({
                    name: 'John Reader',
                    email: 'john@reader.com',
                    rating: 5,
                    comment: 'Excellent book! Highly recommend.',
                }, {
                    name: 'Jane Reviewer',
                    email: 'jane@reviewer.com',
                    rating: 4,
                    comment: 'Great content, a bit worn but still good.',
                });
                books[i].rating = 4.5;
                await books[i].save();
            }
        }

        console.log('Added sample reviews');

        console.log('✅ Database seeded successfully!');
        console.log(`Total Users: ${users.length}`);
        console.log(`Total Books: ${booksData.length}`);

        process.exit(0);
    } catch (error) {
        console.error('❌ Error seeding database:', error);
        process.exit(1);
    }
};

seedDatabase();